package cn.liupeng.catering_management_system.service;

import cn.liupeng.catering_management_system.pojo.Dishes;

public interface DishesMapperService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishesTable
     *
     * @mbggenerated
     */
    // 通过菜品ID注销菜品
    int deleteByPrimaryKey(String dishesid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishesTable
     *
     * @mbggenerated
     */
    // 添加菜品
    int insert(Dishes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishesTable
     *
     * @mbggenerated
     */
    // 添加菜品
    int insertSelective(Dishes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishesTable
     *
     * @mbggenerated
     */
    // 查询菜品
    Dishes selectByPrimaryKey(String dishesid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishesTable
     *
     * @mbggenerated
     */
    // 更新菜品
    int updateByPrimaryKeySelective(Dishes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dishesTable
     *
     * @mbggenerated
     */
    // 更新菜品
    int updateByPrimaryKey(Dishes record);

}
