package cn.liupeng.catering_management_system.service;

import cn.liupeng.catering_management_system.pojo.EmployeesPosition;

public interface EmployeesPositionService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeesPositionTable
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer positionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeesPositionTable
     *
     * @mbggenerated
     */
    int insert(EmployeesPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeesPositionTable
     *
     * @mbggenerated
     */
    int insertSelective(EmployeesPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeesPositionTable
     *
     * @mbggenerated
     */
    EmployeesPosition selectByPrimaryKey(Integer positionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeesPositionTable
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EmployeesPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employeesPositionTable
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EmployeesPosition record);
}
