package cn.liupeng.catering_management_system.pojo;

public class Dishes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishesTable.dishesID
     *
     * @mbggenerated
     */
    private String dishesid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishesTable.dishesPrice
     *
     * @mbggenerated
     */
    private Double dishesprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishesTable.dishesRegisteredDateTime
     *
     * @mbggenerated
     */
    private String dishesregistereddatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishesTable.whoRegisteredDishes
     *
     * @mbggenerated
     */
    private String whoregistereddishes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishesTable.dishesIsCancellation
     *
     * @mbggenerated
     */
    private Integer dishesiscancellation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishesTable.disheslsCancellationDateTime
     *
     * @mbggenerated
     */
    private String disheslscancellationdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dishesTable.whoCancellationDishes
     *
     * @mbggenerated
     */
    private String whocancellationdishes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishesTable.dishesID
     *
     * @return the value of dishesTable.dishesID
     *
     * @mbggenerated
     */
    public String getDishesid() {
        return dishesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishesTable.dishesID
     *
     * @param dishesid the value for dishesTable.dishesID
     *
     * @mbggenerated
     */
    public void setDishesid(String dishesid) {
        this.dishesid = dishesid == null ? null : dishesid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishesTable.dishesPrice
     *
     * @return the value of dishesTable.dishesPrice
     *
     * @mbggenerated
     */
    public Double getDishesprice() {
        return dishesprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishesTable.dishesPrice
     *
     * @param dishesprice the value for dishesTable.dishesPrice
     *
     * @mbggenerated
     */
    public void setDishesprice(Double dishesprice) {
        this.dishesprice = dishesprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishesTable.dishesRegisteredDateTime
     *
     * @return the value of dishesTable.dishesRegisteredDateTime
     *
     * @mbggenerated
     */
    public String getDishesregistereddatetime() {
        return dishesregistereddatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishesTable.dishesRegisteredDateTime
     *
     * @param dishesregistereddatetime the value for dishesTable.dishesRegisteredDateTime
     *
     * @mbggenerated
     */
    public void setDishesregistereddatetime(String dishesregistereddatetime) {
        this.dishesregistereddatetime = dishesregistereddatetime == null ? null : dishesregistereddatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishesTable.whoRegisteredDishes
     *
     * @return the value of dishesTable.whoRegisteredDishes
     *
     * @mbggenerated
     */
    public String getWhoregistereddishes() {
        return whoregistereddishes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishesTable.whoRegisteredDishes
     *
     * @param whoregistereddishes the value for dishesTable.whoRegisteredDishes
     *
     * @mbggenerated
     */
    public void setWhoregistereddishes(String whoregistereddishes) {
        this.whoregistereddishes = whoregistereddishes == null ? null : whoregistereddishes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishesTable.dishesIsCancellation
     *
     * @return the value of dishesTable.dishesIsCancellation
     *
     * @mbggenerated
     */
    public Integer getDishesiscancellation() {
        return dishesiscancellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishesTable.dishesIsCancellation
     *
     * @param dishesiscancellation the value for dishesTable.dishesIsCancellation
     *
     * @mbggenerated
     */
    public void setDishesiscancellation(Integer dishesiscancellation) {
        this.dishesiscancellation = dishesiscancellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishesTable.disheslsCancellationDateTime
     *
     * @return the value of dishesTable.disheslsCancellationDateTime
     *
     * @mbggenerated
     */
    public String getDisheslscancellationdatetime() {
        return disheslscancellationdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishesTable.disheslsCancellationDateTime
     *
     * @param disheslscancellationdatetime the value for dishesTable.disheslsCancellationDateTime
     *
     * @mbggenerated
     */
    public void setDisheslscancellationdatetime(String disheslscancellationdatetime) {
        this.disheslscancellationdatetime = disheslscancellationdatetime == null ? null : disheslscancellationdatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dishesTable.whoCancellationDishes
     *
     * @return the value of dishesTable.whoCancellationDishes
     *
     * @mbggenerated
     */
    public String getWhocancellationdishes() {
        return whocancellationdishes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dishesTable.whoCancellationDishes
     *
     * @param whocancellationdishes the value for dishesTable.whoCancellationDishes
     *
     * @mbggenerated
     */
    public void setWhocancellationdishes(String whocancellationdishes) {
        this.whocancellationdishes = whocancellationdishes == null ? null : whocancellationdishes.trim();
    }
}